# Generated by Django 3.1.3 on 2020-12-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
